---
- name: Remove Grafana
  hosts: localhost
  become: yes
  
  tasks:
  - name: Delete Apt Key
    ansible.builtin.apt_key:
      id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
      state: absent
  - name: Remove grafana.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: absent
  - name: Ensure Grafana is stopped and disabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: no
      state: stopped
  - name: Remove Grafana
    ansible.builtin.apt:
      name: grafana
      state: absent
      
      
      
TEXT
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins

sudo systemctl start jenkins
sudo systemctl enable jenkins